# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mes_utilisateurs:
            entity:
                class: AppBundle:Utilisateur
                property: username

        #     memory: ~
    encoders:
        AppBundle\Entity\Utilisateur: plaintext
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(listQuestionnaire|ajouterQuestionnaire|voirQuestionnaire|login_check|logout)
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: questionnaire_list
            logout:
                path: /logout
                target: /
        accueil:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
