AppBundle\Entity\Questionnaire:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuestionnaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        publie:
            type: boolean
        date:
            type: date
    lifecycleCallbacks: {  }
    manyToOne:
      thematique:
        targetEntity: Thematique
        joinColumn:
          name: thematique_id
          referencedColumnName: id
    manyToMany:
      questions:
        targetEntity: Question
        cascade: ["persist"]
        joinTable:
          name: questionnaire_questions
          joinColumns:
            questionnaire_id:
              referencedColumnName: id
          inverseJoinColumns:
            question_id:
              referencedColumnName: id
              unique: true
