AppBundle\Entity\Utilisateur:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        username:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToMany:
      roles:
        targetEntity: Role
        joinTable:
          name: utilisateurs_roles
          joinColumns:
            utilisateur_id:
              referencedColumnName: id
          inverseJoinColumns:
            role_id:
              referencedColumnName: id
      thematiques:
        targetEntity: Thematique
        joinTable:
          name: utilisateurs_thematiques
          joinColumns:
            utilisateur_id:
              referencedColumnName: id
          inverseJoinColumns:
            thematique_id:
              referencedColumnName: id
    oneToMany:
      examens_apprenant:
        cascade: ["remove"]
        targetEntity: Examen
        mappedBy: apprenant
      questionnaires_entraineur:
        targetEntity: Questionnaire
        mappedBy: entraineur
      examens_correcteur:
        targetEntity: Examen
        mappedBy: correcteur
